### PR TITLE
Feat/basque translation part 2

### PR DESCRIPTION
**Pull request by anediaz**
Hello,

I'm very proud to tell you the Basque translation is finally finished 🎉 
This includes everything, the main README as well as each sub-section files.
I've updated the status of translations in the beginning and the end of the README to set the Basque translation done (not in progress any more).

### CODE REVIEW

**Review by goldbergyoni — APPROVED** [review]
Looks amazing to me

**Comment by goldbergyoni** [comment]
@anediaz That really exciting, not less. Truly amazing work.

Let's promote it now:

1. Put your name on the top of the Basque page?
2. I'll put in the news section
3. I'll tweet (have Twitter handle)
4. Any Basque developer newsgroup to put in?

**Comment by goldbergyoni** [comment]
@all-contributors please add @anediaz for content

**Comment by anediaz** [comment]
Cool !
Please let me verify it one last time before merging it, I'd like to be sure everything is OK. 
I'll let you know when it is good for me. 

In addition, I'll add the last modifications you've requested 😊😊

**Comment by goldbergyoni** [comment]
Oh, I already merged but feel free to PR fixes and I'll merge quickly

**Comment by anediaz** [comment]
No worries, I think I've verified it almost a hundred times, I have to accept it is impossible to reach the perfection 🤣

**Comment by goldbergyoni** [comment]
I like this:)

Are you a freelance?

**Comment by anediaz** [comment]
No I'm not, I'm an employee in a French AI company, I work as a FrontEnd developer.
However, I have a second occupation, as self-employed. I make illustrations of technical conferences, presentations... I love using visual representations to explain technical concepts.

I'll add the 4 points you asked me in the previous comment and I'll create a PR.

Thank you!

**Comment by anediaz** [comment]
> @anediaz That really exciting, not less. Truly amazing work.
> 
> Let's promote it now:
> 
> 1. Put your name on the top of the Basque page?
> 2. I'll put in the news section
> 3. I'll tweet (have Twitter handle)
> 4. Any Basque developer newsgroup to put in?

Point 1-> Where should I put my name, exactly?
Point 3 -> This is my Twitter handle: ane_naiz
Point 4 -> You can mention these two websites if you wish :
- http://ixa.si.ehu.es/
- https://iparra.eus/

**Pull request merged**
