### PR TITLE
fix russian translation typos

### PR DESCRIPTION
**Pull request by vladthelittleone**
- translate comments
- fix typos

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@contributorpw Want to review this?

**Comment by goldbergyoni** [comment]
@vladthelittleone Thanks for making this guide better and helping Russian developers conform to best practices!

**Comment by goldbergyoni** [comment]
@contributorpw @vladthelittleone  

I don't know how to resolve this conflict as it's in Russian, could you help plz?

**Comment by goldbergyoni** [comment]
@vladthelittleone The ball is in your court, no rush - just to ensure we're on the same page

**Comment by vladthelittleone** [comment]
@goldbergyoni thanks. I’ll check all the edits again and resolve conflicts.

**Comment by goldbergyoni** [comment]
> @goldbergyoni thanks. I’ll check all the edits again and resolve conflicts.

Let me know whether I can help?

**Comment by vladthelittleone** [comment]
@goldbergyoni resolved conflicts and fixed typos

**Comment by kevynb** [comment]
@goldbergyoni should we merge this now or wait for @contributorpw ? He seems to not be available at the moment

**Comment by kevynb** [comment]
Sorry @vladthelittleone can you resolve the conflicts ? And then I will merge :)

**Comment by vladthelittleone** [comment]
@kevynb 👍

**Review by edbond88 — DISMISSED** [review]

**Comment by vladthelittleone** [comment]
@kevynb done!)

**Comment by kevynb** [comment]
Great! 🎆 🎊 

@allcontributors-bot please add @vladthelittleone for translation!

**Review by kevynb — APPROVED** [review]

**Comment by kevynb** [comment]
@all-contributors please add @vladthelittleone for translation!

**Pull request merged**
