### PR TITLE
#936 Resolve wrong code example in 3.3 in README

### PR DESCRIPTION
**Pull request by burkybang**
Resovle https://github.com/goldbergyoni/nodebestpractices/issues/936

### CODE REVIEW

**Review by rluvaton — APPROVED** [review]

**Comment by rluvaton** [comment]
Hi @burkybang, Could you please fix it in the `README.basque.md` file too

**Comment by burkybang** [comment]
@rluvaton Done

**Review by rluvaton — APPROVED** [review]
Thanks!

**Review by sher-s7 — APPROVED** [review]

**Comment by goldbergyoni** [comment]
@burkybang Awesome catch ✨, Could you just please fix the merge conflict?

**Comment by goldbergyoni** [comment]
@burkybang Bringing this up, are you challenged with the conflict and need help?

**Comment by burkybang** [comment]
Oh, I didn't realize I still needed to do something. Yeah, maybe I do need help.

**Comment by rluvaton** [comment]
@goldbergyoni I don't see a merge conflict, I think it resolved automatically

**Comment by rluvaton** [comment]
@all-contributors please add @burkybang for content

**Pull request merged**
