### PR TITLE
Backport README.md from master and update README.korean.md

### PR DESCRIPTION
**Pull request by songe**
Here is the list of all the changes I've made in this PR:

- Merge branch 'korean-translation' into master
- Remove all ^M characters from README.korean.md
- Update 1.1-2.7 & 4 to sound more natural in Korean
- Backport `README.md` changes from `master` into `README.korean.md`

It may look like a large change since I removed all the ^M characters from the file, but the actual changes are much smaller and organized by commits.

👉 [Preview](https://github.com/songe/nodebestpractices/blob/master/README.korean.md)

### CODE REVIEW

**Comment by kevynb** [comment]
Hi @songe, nice work! Any reason you are targeting the branch korean-translation instead of master? I'm asking given that the Korean translation is also available on the master branch.

**Comment by songe** [comment]
@kevynb Thanks! I actually created a PR against `master`, but then noticed that the guidelines in https://github.com/goldbergyoni/nodebestpractices/issues/94 said to merge changes into [korean-translation](https://github.com/goldbergyoni/nodebestpractices/tree/korean-translation) branch. 

Personally, I think it'd make more sense to merge these directly into `master`, and I'd be happy to update the PR to target `master` instead.

**Comment by songe** [comment]
@kevynb I've rebased the branch against `master` with `korean-translation` branch merged it. The change is master-ready, and I've also changed the PR base to master.

**Comment by kevynb** [comment]
I guess we should wait for another maintainer to chime before merging into master since that’s what the contributing docs says.

@goldbergyoni for example?

**Comment by songe** [comment]
@kevynb @goldbergyoni Any updates on this? I want to continue working on this and translate the rest of the document, but I'd like to make sure this gets merged in first since this is a big change.

**Comment by goldbergyoni** [comment]
@songe  Thanks for the great improvements and sorry waiting - was a bit busy due to the crazy & hectic worldwide situation. Going to be much more available now.

@all-contributors please add @songe  for content

**Pull request merged**
