### PR TITLE
Translate README.korean.md

### PR DESCRIPTION
**Pull request by cisco0808**

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@cisco0808 Welcome and many thanks for making this guide better!

@BrunoScheufler Who is our Turkish reviewer?

**Comment by BrunoScheufler** [comment]
@goldbergyoni I'm not completely sure, did we assign somebody? I remember checking out some Turkish content, but apart from formatting and code I can't really do much here 🤔

**Comment by goldbergyoni** [comment]
Oh! I'm truly sorry, I mixed this with another PR that deals with Turkish 🤭😞

@uronly14me Would you kindly keep the Korean translation high standards and approve this PR? 💚

**Review by uronly14me — APPROVED** [review]

**Comment by uronly14me** [comment]
I have just checked and it is good. Thanks!

**Comment by kevynb** [comment]
Great! Thanks @cisco0808 for taking the time to translate those new sections and thanks to @uronly14me for proofreading :)

**Comment by kevynb** [comment]
@all-contributor please add @cisco0808 for translation

**Review by kevynb — APPROVED** [review]

**Comment by kevynb** [comment]
@all-contributors please add @cisco0808 for translation

**Comment by kevynb** [comment]
Damn! I removed the wrong comment!

I said thanks @cisco0808 for translating those new sections and thanks @uronly14me for proofreading them

**Pull request merged**
