### PR TITLE
Translate the rest of README.korean.md

### PR DESCRIPTION
**Pull request by songe**
Translate `README.korean.md`

This PR essentially translates the rest of `README.korean.md`. After this PR, we'll only need to translate the sections into Korean.

- Update the Collaborators section
- Update intro & other sections to sound more natural in Korean
- Fix typos
- Add the missing code example in section 3.4
- Translate sections 6 & 7
- Import @mindock's changes (84c357b3c73b84a85568f7134c7c6444cfcb5d9e) from [korean-translation]( https://github.com/goldbergyoni/nodebestpractices/tree/korean-translation) branch

Additionally,
- Translate `sections/projectstructre/breakintcomponents.korean.md`

### CODE REVIEW

**Comment by songe** [comment]
Please review, @goldbergyoni !

**Comment by goldbergyoni** [comment]
@songe Looks amazing, did you add youself to the top of the Korean page?

@all-contributors please add @songe for content

**Comment by goldbergyoni** [comment]
@all-contributors please add @songe for content

**Comment by songe** [comment]
> @songe Looks amazing, did you add youself to the top of the Korean page?

@goldbergyoni I haven't. I can do that in the next PR :) Are you talking about `README.korean.md` file, or are you talking about a different file?

**Comment by goldbergyoni** [comment]
Both to .korean.md and to the bottom of the main readme.md like shown in this pic 👇

image

**Comment by songe** [comment]
@goldbergyoni Ok, so I understood you correctly the first time. The changes are in https://github.com/goldbergyoni/nodebestpractices/pull/671

**Pull request merged**
