### PR TITLE
Add chapter 7 translated in chinese

### PR DESCRIPTION
**Pull request by ZhyMC**
This chapter is harder to translate, but i finished the work more carefully.

### CODE REVIEW

**Comment by ZhyMC** [comment]
https://github.com/ZhyMC/nodebestpractices/blob/add-chapter-7-translated/README.chinese.md

**Comment by goldbergyoni** [comment]
@ZhyMC Awesome! Since I my Chinese speaking skills need some polish, I'll ask for another reviewer

@MattJin Would you like to briefly review?

**Review by goldbergyoni — APPROVED** [review]
Based on Google translate, it looks great:)

**Comment by goldbergyoni** [comment]
@ZhyMC Awesome! 🏅

@all-contributors please add @ZhyMC  for content

**Pull request merged**
