### PR TITLE
Turkish Translation

### PR DESCRIPTION
**Pull request by konuralpt**
I couldn't push the other 'Turkish Translation' pull request because of access rights. Sorry for reopening

- [x] Code Style Practices
- [ ] Error Handling
- [ ] Performance
- [ ] Production
- [ ] Project Structure
- [ ] Security
- [ ] Testing and Quality

### CODE REVIEW

**Comment by BrunoScheufler** [comment]
@konuralpt hey there! I see a lot of awesome progress 🚀 Should we already merge this in or wait for further changes? It's no problem to merge it and open subsequent PRs for further progress 👍

**Comment by konuralpt** [comment]
@BrunoScheufler Hey thanks! For sure there will be changes but it will take time. So you can merge it and i will open PR when it's done. Thank you!

**Comment by i0natan** [comment]
@konuralpt @BrunoScheufler Shall we also merge to master and a Turkish flag to translations?

If(translations.coverage >50% && translations.isTranslated('homepage')){
mergeToMasterAndPutFlag() 🚀 
}

**Comment by goldbergyoni** [comment]
@konuralpt @BrunoScheufler Is most of the main page translated? If yes, why not, put a flag?

**Comment by goldbergyoni** [comment]
@BrunoScheufler I see that it a remarkable amount of work was invested here, is this work blocked or just fell between the cracks?

**Comment by BrunoScheufler** [comment]
@goldbergyoni I’m not exactly sure but I think we should try to get this done, somehow progress cut off a few months ago

**Comment by goldbergyoni** [comment]
@konuralpt How much approximately is translated? if >80%, we should maybe merge

**Comment by konuralpt** [comment]
@goldbergyoni Hi! sorry for the very late reply. I couldn't deal with this PR. Turkish translation is actually not even close to 80%, so we better keep this PR open right now.

**Pull request closed without merging**
