### PR TITLE
fix: small error

### PR DESCRIPTION
**Pull request by 0xflotus**

### CODE REVIEW

**Review by elektronik2k5 — APPROVED** [review]

**Review by js-kyle — APPROVED** [review]

**Comment by js-kyle** [comment]
@all-contributors please add @elektronik2k5 for content

**Comment by 0xflotus** [comment]
> @all-contributors please add @elektronik2k5 for content

It's not a problem, but the PR was from me, @elektronik2k5 just approved it :D

**Comment by iqfy-kyle** [comment]
@all-contributors please add @0xflotus for content

Sorry about that @0xflotus !

**Comment by 0xflotus** [comment]
> @all-contributors please add @0xflotus for content
> 
> Sorry about that @0xflotus !

As mentioned above, no problem :D

**Pull request merged**
