### PR TITLE
Added the conversation as a detailed explanation for create layers

### LINKED ISSUE #393: 1.2 Layer your components, keep Express within its boundaries
First I want to say a huge thank you for this resource. As someone just starting out it's great to see the community coming together to provide this. I'm was going over the list and on the layering components (1.2), I get the overall picture but when clicking on more details there is just a gif. Is there anyway to give a bit more detail on this page? I see that there is quite a nice detailed answer in #252 , I don't mind summarizing that into a pull request and giving the people who answered credits.

### PR DESCRIPTION
**Pull request by bikingbadger**
Using the conversation in #252 I updated the create layers section with more detail. I added the credits of those involved. Please let me know if anything should be updated or changed.

This will close #393

### CODE REVIEW

**Comment by js-kyle** [comment]
@bikingbadger thanks! great idea to capture the discussion that has happened over into the content.

**Comment by i0natan** [comment]
@bikingbadger Thanks for this important contribution 🎆 

I'm not sure whether the discussion there is exhaustive enough to summarize this topic, I'd like to work on it with you and improve a bit. For example, if we discuss layering we should mention the various techniques to achieve this (e.g. clean architecture, hexagonal, n-tier, DDD, onion, etc).

I'll share with you some additional insights we should cover in few days, cool?

/remind me in 4 days

**Comment by bikingbadger** [comment]
@i0natan Great, glad to work together on this. I'm still very much learning so I was just looking to flesh out this section a bit more as it was quite bare. I saw the conversation and that is why I referenced it. I'd really love some further information on the subject as I'm starting on a side project and trying to use what I'm learning here in the actual project.

**Comment by bikingbadger** [comment]
@i0natan you up for discussing this in a bit more depth so I can make the changes?

**Comment by i0natan** [comment]
@bikingbadger Sorry for the delay, I'm fully up now for discussing this.

Are you available to run this discussion over the next week simultaneously? I've several ideas for improvement to share

Note to self: express->web framework, mock->test, mention few layering techniques, better diagram, mention the great movie about clean architecture, consider separating into 2 bullets: entry points vs the domain structure, code exampe to share, etc

**Comment by bikingbadger** [comment]
What do you mean simultaneously? Using the comments here or getting on skype or something to knock this issue out.
I'm in Israel so not sure how your timezones work but sure we can work something out. I'm here to make any changes you reckon would be good for the PR

**Comment by i0natan** [comment]
@bikingbadger Whatever works for you, I meant just exchanging here messages every day (once a day is 100% fine or whatever pace suits your timeline). 

My thoughts: This bullet actually handle two different topics: (A) separate entry-points from the app - express, CLI, Electron, whatever app should be isolated from the logic/data and the app internal (B) separate the domain - the app logic should be isolated from all the technical stuff (DB, log, etc). This principle is a commonality of architecture types. Let's split?

## About 'Separate entry point from the app' 
 - Motivation: simply put, if you mix your access point (e.g. api objects) with the rest of the app, for example by passing {req, res} to many methods, then your app become coupled to one technology/access and once you want to consume it using a different technology (e.g. add graphql, desktop app, CLI, etc) - a big refactor is needed. Moreover, it's much harder to unit test internal modules as they depend on API/network object. Does that make sense?
- Simple example code: show express route destructuring the necessary properties from Express req and passing into the business layer scalars and not a req object
- Anti-pattern example - the opposite from above
- Comprehenaive example code: I would show an example of a simple app, where there is a folder 'Entry points' that holds all the app doors: API, CLI, etc, and other folders for the internals. I have an example for this
- Diagram: like this maybe? can probably refine it a bit
http://snpy.in/7yTgLn

## About 'Isolate the domain' - let's discuss soon



Thoughts?

p.s. did you read our [content writing guidelines](https://github.com/i0natan/nodebestpractices/blob/master/.operations/writing-guidelines.md)?

**Comment by i0natan** [comment]
@bikingbadger See my detailed answer above. Shall we have a phone call to discuss this or is it clear enough?

**Comment by bikingbadger** [comment]
Hi Natan,
Sorry about the delay. Been bit bogged down at work. I'll add those changes that you proposed and push it hopefully later today.

**Comment by i0natan** [comment]
> Sorry about the delay. Been bit bogged down at work. I'll add those changes that you proposed and push it hopefully later today

Sure, at your convenient time. LMK whether a phone call might be helpful (live in Israel too)

**Comment by goldbergyoni** [comment]
@bikingbadger Shall we push this?

**Comment by bikingbadger** [comment]
Hi Yoni,
Sorry this one fell completely through the cracks for me. Apologies. Can we look at this in the new year? Do you still think it's relevant?

**Comment by goldbergyoni** [comment]
@bikingbadger I think it's highly relevant and will gladly have a chat/phone with you on it

**Comment by bikingbadger** [comment]
Great. I have been trying to see where this has disappeared in my repo's for the pull request. I have it locally but I have lost the connection to the PR on my fork. Should I create another PR and close this one and we can continue from there? I'd be happy to talk on the phone, just let me know how to get my number to you or vice versa

**Comment by goldbergyoni** [comment]
@bikingbadger Let start by discussing this by phone and then determine how to put our thoughts on paper. Would you mind shooting me an email to schedule a talk?

https://testjavascript.com/contact-2/

p.s. You coming to the local Node.js conf?

**Pull request closed without merging**
