### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by Lenora1234-art**
repository-open-graph-template
or maybe- give them explicit instructions about what the hell is going on instead of letting their life blow apart. Provide detailed explanations to patients and staff of how their files or information could be breached and what can be done or is being done to prevent that. Maybe even adopting a plan from a noteworthy source. 
for example:
BSWNeurotexas complies with the EU-U.S. Privacy Shield Framework and/or the Swiss-U.S. Privacy Shield  Framework(s), as applicable) as set forth by the U.S. Department of Commerce regarding the collection, use, and retention of personal information transferred from both European Union and/or Switzerland, as applicable, to the United States.  BSWNeurotexas has certified to the Department of Commerce that it adheres to the Privacy Shield Principles.  If there is any conflict between the terms in this privacy policy and the Privacy Shield Principles, the Privacy Shield Principles shall govern.  To learn more about the Privacy Shield program, and to view our certification, please visit https://www.privacyshield.gov/.

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@Lenora1234-art Welcome and thanks ☀️

Can you clarify this kindly - Is this a general security.md for our repo although it doesn't include any production installs, just a book? It it necessary? I noted it is now just a template, what would you write there?

**Comment by VinayaSathyanarayana** [comment]
I am lost on why there is reference to patients and staff

**Comment by goldbergyoni** [comment]
@josh-hemphill Shall we add a security bullet about security.md that explains why components/packages should include this in their root?

This specific PR doesn't elaborate about this, it's just a trigger to consider this topic

**Comment by josh-hemphill** [comment]
@goldbergyoni sounds like a good idea, I can get started on it; is there already an item about security disclosures in general? 
I wonder if it should all fall under that broader item, because it reminded me that for server-side code, if Node is acting as a web server and serving the root of a domain it should also provide a `/.well-known/security.txt` for security disclosures, similar to `security.md`.

**Comment by goldbergyoni** [comment]
@josh-hemphill No, nothing on this. It's a good idea to aggregate all of these ideas into a single bullet.

Maybe @lirantal can spare advice and refer to interesting content/tools/articles on security disclosures.

**Comment by js-kyle** [comment]
@goldbergyoni @josh-hemphill we have these two items in the generic security bullet https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/commonsecuritybestpractices.md#-have-a-securitytxt-file-production https://github.com/goldbergyoni/nodebestpractices/blob/master/sections/security/commonsecuritybestpractices.md#-have-a-securitymd-file-open-source

As neither of them relate to Node.js (rather, general web security) I think they belong there rather than in main bullets

**Comment by lirantal** [comment]
My 2 cents here:
1. Yes, a `SECURITY.md` file should definitely be added and provide information on what the disclosure process is like, the SLA, the contacts, etc. I've actually written about that as part of my work with the Verdaccio project/team to also enable a SECURITY.md file for them, see here: https://snyk.io/blog/devsecops-tools-for-open-source-projects-in-javascript-and-node-js/
2. Note that the SECURITY.md should be a file in a project, not something in a package or a website. 
3. A website, should expose similar information in a structured way via the security.txt draft, which I've got a module for express for over here that shows the expected inputs: https://snyk.io/advisor/npm-package/express-security-txt

**Comment by goldbergyoni** [comment]
@js-kyle Good point, I guess this should get closed? 🤔

@lirantal 💚

**Comment by goldbergyoni** [comment]
@Lenora1234-art Nice discussion, it seems most are supportive for putting this within the generic security bullet, do we want to enrich it or is it good enough for now?

**Pull request closed without merging**
