### PR TITLE
Russian translation. Reaction to recent changes 2019/09

### PR DESCRIPTION
**Pull request by contributorpw**
There is the last changes sync and the new block-loop section.

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@contributorpw Looks great, very organized and easy to follow 🏅 

Shall we merge the Russian translation into master?

**Comment by contributorpw** [comment]
> Shall we merge the Russian translation into master?

I would like to support this every day.

I'm still reading some recommendations and looking for additional information on these topics. It seems to me that the textbooks of the future may be just this repo.

**Comment by goldbergyoni** [comment]
@contributorpw So just to confirm, I'm merging now to master, OK? or shall I wait?

**Comment by contributorpw** [comment]
It's OK

**Pull request merged**
