### PR TITLE
Add Winston logger to 2.7 (loggers)

### PR DESCRIPTION
**Pull request by denisecase**
Adding Winston as a top option under 2.7 loggers.  Reference https://www.npmtrends.com/winston-vs-pino-vs-bole-vs-log4js

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@denisecase Winston should be in the list. I would suggest that it should appear under Pino because:

1. We conducted a benchmark last year which showed that Pino was tremendously faster
2. Winston main examples show logging to file system which encourages a bad practice (logging not to stdout)

I'm curious to hear your thoughts

@kevynb Thoughts on this?

**Comment by josh-hemphill** [comment]
^
I really like [pino's assertion in their readme](https://www.npmjs.com/package/pino#transports--log-processing). 
Though I noticed that the detailed explanation instead puts Winston first; should the detailed explanation also be updated?
Perhaps the Readme should only assert that you need to adopt a single structure for all your logging, so that (as pino points out) an external system can predictably parse and consume your logging.

**Comment by denisecase** [comment]
Adding Winston after Pino sounds better - thanks for the info!

**Comment by kevynb** [comment]
@goldbergyoni I second you on that. 

@denisecase I dug out [the issue where spoke about that](https://github.com/goldbergyoni/nodebestpractices/issues/684) for you in case you want more context.

@denisecase or @josh-hemphill Would you care to make a PR to change the to the detailed explanation?
If not, I'll find some time to do it later.

**Comment by denisecase** [comment]
@kevynb The discussion is excellent and I agree Winston is not best practices. That's why this guide is so helpful.  I'd recommend we remove all Winston example code and change the opening to:  

We all love console.log but obviously, a reputable and persistent logger like Pino (a [newer option focused on performance](https://github.com/goldbergyoni/nodebestpractices/issues/684)) is mandatory for serious projects.

**Comment by denisecase** [comment]
This is no longer best practice - RP can be closed.

**Pull request closed without merging**
