### PR TITLE
docs: make translation of "otherwise" consistent

### PR DESCRIPTION
**Pull request by Foo-x**
There are "さもないと" and "さもなければ" for the translations of "Otherwise".
I made them consistent to "さもないと".

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@Foo-x Welcome 🎉

@YukiOta Kindly review?

**Comment by YukiOta** [comment]
@Foo-x @goldbergyoni 
LGTM! Thank you for fixing!

**Review by YukiOta — APPROVED** [review]
@Foo-x @goldbergyoni
LGTM! Thank you for fixing!

**Comment by elektronik2k5** [comment]
@goldbergyoni I remember that GitHub has a concept of file owners, which IIRC, allows automatic assigning of pull requests to their respective modified file owners. We could use this mechanism to automate translation PRs, can't we?

**Comment by goldbergyoni** [comment]
> @goldbergyoni I remember that GitHub has a concept of file owners, which IIRC, allows automatic assigning of pull requests to their respective modified file owners. We could use this mechanism to automate translation PRs, can't we?

Sounds very relevant, what should I Google for exactly?

**Comment by elektronik2k5** [comment]
@goldbergyoni I haven't looked into this, but here are the relevant docs: https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-code-owners

**Pull request closed without merging**
