### PR TITLE
added require for the testing package

### PR DESCRIPTION
**Pull request by keyrwinz**

### CODE REVIEW

**Comment by kevynb** [comment]
Hello @keyrwinz, thanks for taking the time to contribute to our repository. However, I don't really see the purpose of the code you added. Given that this example is about a "production" node server, why would one use supertest here?

Could you please elaborate?

**Comment by keyrwinz** [comment]
> Hello @keyrwinz, thanks for taking the time to contribute to our repository. However, I don't really see the purpose of the code you added. Given that this example is about a "production" node server, why would one use supertest here?
> 
> Could you please elaborate?

Hi, It's for the example in testing API in-process, it stated there it uses supertest package but never declared in the code.

**Comment by kevynb** [comment]
Ah yes! I missed that in the diff. I re-read the whole file and you’re indeed right, we’re talking about supertest but not using it :)
That’s a good catch!

Can you update the typescript example to use an import instead of a require?

**Comment by keyrwinz** [comment]
> Ah yes! I missed that in the diff. I re-read the whole file and you’re indeed right, we’re talking about supertest but not using it :)
> That’s a good catch!
> 
> Can you update the typescript example to use an import instead of a require?

resolved in 227e00d

**Comment by kevynb** [comment]
@all-contributors please add @keyrwinz for content

**Pull request merged**
