### PR TITLE
[FEAT] Add news Brazilian Portuguese translation

### PR DESCRIPTION
**Pull request by taranttini**
[FEAT] Add news Brazilian Portuguese translation

Rearrange section 4 items, same as english materia

### CODE REVIEW

**Comment by goldbergyoni** [comment]
Yo @taranttini , welcome aboard and thanks for the great contribution! 🌻

@marcelosdm Would you kindly review this PR?

**Review by marcelosdm — COMMENTED** [review]
Great work @taranttini !!
Thank you so much for your contribution!

**Review by marcelosdm — APPROVED** [review]

**Comment by rluvaton** [comment]
> @goldbergyoni I reviewed, but it seems that I don't have access to approve it! 

I'll approve it for you, thanks man!

**Review by rluvaton — APPROVED** [review]

**Comment by goldbergyoni** [comment]
@rluvaton Once you have an approval from a friend like @marcelosdm and you approved it, you can merge

@taranttini Super-awesome

@all-contributors please add @taranttini  for content

**Pull request merged**
