### PR TITLE
Added note on Security.txt file

### PR DESCRIPTION
**Pull request by VinayaSathyanarayana**
Added the note to have security.md file

### CODE REVIEW

**Comment by VinayaSathyanarayana** [comment]
@goldbergyoni - Please review and merge this PR

**Comment by kevynb** [comment]
Hello, thanks for your contribution :)

Are you talking about a Security.md file that is visible to contributors of an open source project in the project repository?

Or maybe you are talking about a file that can be accessed on a running production server? If that’s the second option, then shouldn’t that be a security.txt file?

In both case I think that we could formulate it more explicitly, because if I’m confused, others might be :)

**Comment by VinayaSathyanarayana** [comment]
Thanks for pointing it out. Will mention both explicitly.

**Comment by VinayaSathyanarayana** [comment]
Closed in favor of #622

**Pull request closed without merging**
