### PR TITLE
Update link to Korean translation

### PR DESCRIPTION
**Pull request by songe**
Make the link to Korean translation point to the [fork](https://github.com/songe/nodebestpractices-korean/blob/master/README.korean.md) rather than `README.korean.md` in the main repo, since the fork will contain the latest translations and changes.

Also add translation additional translations for sections 1.4, 1.5, and 2.1.

Please review, @goldbergyoni @kevynb

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@songe Great progress!

Why the right thing is linking to an external repo (fork) rather to an internal page?

**Comment by songe** [comment]
@goldbergyoni Since the fork will have the latest translations and changes before it gets merged in to master, I thought it'd be easier for the readers to have it point to the fork, at least while the Korean translation is still a work in progress. [French](https://github.com/gaspaonrocks/nodebestpractices/blob/french-translation/README.french.md) & [Spanish](https://github.com/i0natan/nodebestpractices/blob/spanish-translation/README.spanish.md) translations do the same thing and I thought I'd follow suit.

**Comment by songe** [comment]
@goldbergyoni Any updates on this? I plan on leaving the link only while the Korean translation is still a WIP. Once all the pages have been translated, I plan on revert it back to point to the main repo's README.korean.md

**Comment by goldbergyoni** [comment]
@songe Sorry for the delay, we had a discussion whether translations should live on a fork. Our guideline is to strive having all the content here but it's OK to land a translation on a fork for <2 months and then it should get merged. Does this resonate with you?

Kindly resolve conflict and I'll merge immediately. Sorry for keeping you waiting.

**Comment by songe** [comment]
I just saw the comment. How can I reopen the PR so I can resolve conflicts to bring it back to a resolvable state? I can also remove the link to the fork during the rebase, since I guess I wasn't translating as actively as I though I would.

**Comment by songe** [comment]
@goldbergyoni I just saw your comment. How can I reopen the PR so I can resolve conflicts to bring it back to a resolvable state? I can also remove the link to the fork during the rebase, since I guess I wasn't translating as actively as I though I would.

**Comment by songe** [comment]
Reopen
--
Angie

**Pull request closed without merging**
