### PR TITLE
Added all new dutch translation files

### PR DESCRIPTION
**Pull request by Stephenklop**
I created all the new translation files for the dutch language.
Would you be able to announce that we are working on dutch?

### CODE REVIEW

**Comment by rluvaton** [comment]
Thank you very much!

@goldbergyoni do you know anyone who know Dutch and can review this?

**Comment by rluvaton** [comment]
Thank you very much!

@goldbergyoni Can you please take a look, should we create empty translations files without the actual translations?

(He translated the README file (but I need someone to review it as I don't know Dutch)

**Comment by goldbergyoni** [comment]
@Stephenklop @rluvaton Typical workflow:

1. Do minor initial work
2. PR to dutch-translation (not master, otherwise ppl will click dutch.readme.md get disappointed)
3. PR to master Dutch announcement with link to dutch-translation (branch already exists)
4. Translate locally and collaborate with others
5. Occasionally PR to dutch-translation to save work
6. Once Home page is ready, PR to **master** with link the translation
7. Translate internal pages

Sensible?

**Comment by Stephenklop** [comment]
Yes! Thank you! Will change that straight away

**Comment by goldbergyoni** [comment]
@Stephenklop Can I close this?

**Comment by goldbergyoni** [comment]
@Stephenklop One more question - What is the status? I remember seeing most of the files translated, should not we merge to master and promote this?

**Comment by goldbergyoni** [comment]
I would guess that this PR can be closed. If not, please LMK and I'll re-open

**Pull request closed without merging**
