### PR TITLE
French translation

### PR DESCRIPTION
**Pull request by forresst**
This PR contains the complete translation of the README.md (README.french.md) and the complete French translation of 57 points (*.french.md). The remaining 29 points to be translated are a copy of the original English version in the *.french.md files).

This choice has been discussed with [Yoni Goldberg](https://github.com/goldbergyoni/nodebestpractices/issues/129).

It is possible to see the remaining translations [here](https://github.com/forresst/nodebestpractices/issues/1)

Note that the files are up to date with the English version.

I want to thank @MrYamous and @tkhadir for their very precious help

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@forresst @tkhadir @MrYamous Formidable!💜

Amazing work. I used to know French, my family is from Marseille:), but I don't remember enough so @kevynb might have a quick look and approve

We should celebrate this translation by putting on news + tweeter after next week. Is there some Node.js group/form for Node.js to publish there?

Make sure to put your names on top of the French translation

**Comment by tkhadir** [comment]
thanks @goldbergyoni 

All the merits go to @forresst  😄 , it is a committed person with whom we can carry out projects to end.

**Comment by forresst** [comment]
> We should celebrate this translation by putting on news + tweeter after next week. Is there some Node.js group/form for Node.js to publish there?

I guess you're looking for a French-speaking twetter account? Sorry I don't know any twetter.

> Make sure to put your names on top of the French translation

I looked at the other translations to try to be consistent with the others. But I don't see exactly where to put it at the top?

**Review by goldbergyoni — APPROVED** [review]
Looks super-awesome to me

**Comment by goldbergyoni** [comment]
@all-contributors please add @tkhadir for content

**Comment by goldbergyoni** [comment]
@all-contributors please add @MrYamous for content

**Comment by goldbergyoni** [comment]
@all-contributors please add @MrYamous for content

**Comment by goldbergyoni** [comment]
@all-contributors please add @MrYamous for content

**Comment by goldbergyoni** [comment]
@forresst 

About your names at the top. -Just choose an adequate location

About forums - Is there any French newsgroup (e.g. Facebook/Discord), where we can promote this translation?

**Pull request merged**
