### PR TITLE
add markdownlint-cli

### PR DESCRIPTION
**Pull request by js-kyle**

### CODE REVIEW

**Comment by oshliaer** [comment]
That's cool!

Thanks @js-kyle !

**Comment by oshliaer** [comment]
But. Sorry You have to undo changes of this.

My main complaint is that you should not break the paragraph. This violates the consistency of the translation. It also violates the control of translation strings.

Example

_Correct_
```md
1114 Deep specialist in JavaScript and its ecosystem — React, Node.js, MongoDB, pretty much anything that involves using JavaScript/JSON in any layer of the system — building products using the web platform for the world’s most recognized brands. Individual Member of the Node.js Foundation, collaborating on the Community Committee's Website Redesign Initiative.
```

_Correct_
```md
1114 Deep specialist in JavaScript and its ecosystem — React, Node.js, MongoDB, pretty much anything that involves using JavaScript/JSON in any layer of the system — building products using the web platform for the world’s most recognized brands. Individual Member of the Node.js Foundation, collaborating on the Community Committee's Website Redesign Initiative.
```

_Incorrect_
```md
1427 Deep specialist in JavaScript and its ecosystem — React, Node.js, MongoDB, pretty much anything that involves using
1428 JavaScript/JSON in any layer of the system — building products using the web platform for the world’s most recognized brands.
1429 Individual Member of the Node.js Foundation, collaborating on the Community Committee's Website Redesign Initiative.
```

**Comment by oshliaer** [comment]
Please forbid any `"MD013": {"line_length": },`

**Comment by js-kyle** [comment]
@oshliaer I've created https://github.com/goldbergyoni/nodebestpractices/issues/552

**Pull request merged**
