### PR TITLE
Spanish translation: Add reviewed translations for One Paragraph Explainers

### PR DESCRIPTION
**Pull request by desko27**
## ⛏ What work is being done here?

Only "One Paragraph Explainer" from inner sections are being translated in this PR. For further discussion and planning please take a look at the official spanish translation issue: #95.

## 📝 Task list
- [x] Translate 51 "one paragraph explainers" to a private Excel (by Seth)
- [ ] Carefully review and polish translations (by desko27)
- [ ] Actually add them to the PR (by desko27)

## ✅ Sections 1-5 → Translations from 1 to 34 - 100%
- [x] 1) [Structure your solution by components](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/breakintcomponents.md)
- [x] 2) [Layer your app, keep Express within its boundaries](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/createlayers.md)
- [x] 3) [Wrap common utilities as npm packages](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/wraputilities.md)
- [x] 4) [Separate Express 'app' and 'server'](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/separateexpress.md)
- [x] 5) [Use environment aware, secure and hierarchical config](https://github.com/i0natan/nodebestpractices/blob/master/sections/projectstructre/configguide.md)
- [x] 6) [Use Async-Await or promises for async error handling](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/asyncerrorhandling.md)
- [x] 7) [Use only the built-in Error object](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/useonlythebuiltinerror.md)
- [x] 8) [Distinguish operational vs programmer errors](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/operationalvsprogrammererror.md)
- [x] 9) [Handle errors centrally. Not within middlewares](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/centralizedhandling.md)
- [x] 10) [Document API errors using Swagger](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/documentingusingswagger.md)
- [x] 11) [Exit the process gracefully when a stranger comes to town](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/shuttingtheprocess.md)
- [x] 12) [Use a mature logger to increase errors visibility](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/usematurelogger.md)
- [x] 13) [Test error flows using your favorite test framework](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/testingerrorflows.md)
- [x] 14) [Discover errors and downtime using APM products](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/apmproducts.md)
- [x] 15) [Catch unhandled promise rejections](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/catchunhandledpromiserejection.md)
- [x] 16) [Fail fast, validate arguments using a dedicated library](https://github.com/i0natan/nodebestpractices/blob/master/sections/errorhandling/failfast.md)
- [x] 17) [Carefully choose your CI platform](https://github.com/i0natan/nodebestpractices/blob/master/sections/testingandquality/citools.md)
- [x] 18) [Monitoring!](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/monitoring.md)
- [x] 20) [Make your app transparent using smart logs](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/smartlogging.md)
- [x] 21) [Delegate anything possible (e.g. static content, gzip) to a reverse proxy](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/delegatetoproxy.md)
- [x] 22) [Lock dependencies](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/lockdependencies.md)
- [x] 23) [Guard and restart your process upon failure (using the right tool)](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/guardprocess.md)
- [x] 24) [Utilize all CPU cores](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/utilizecpu.md)
- [x] 25) [Create a maintenance endpoint](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/createmaintenanceendpoint.md)
- [x] 26) [Sure user experience with APM products](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/apmproducts.md)
- [x] 27) [Make your code production-ready](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/productioncode.md)
- [x] 28) [Measure and guard the memory usage](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/measurememory.md)
- [x] 29) [Get your frontend assets out of Node](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/frontendout.md)
- [x] 30) [Be stateless, kill your Servers almost every day](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/bestateless.md)
- [x] 31) [Use tools that automatically detect vulnerable dependencies](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/detectvulnerabilities.md)
- [x] 32) [Assign ‘TransactionId’ to each log statement](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/assigntransactionid.md)
- [x] 33) [Set NODE_ENV = production](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/setnodeenv.md)
- [x] 34) [Use an LTS release of Node.js in production](https://github.com/i0natan/nodebestpractices/blob/master/sections/production/LTSrelease.md)

## 🔄 Section 6 → Translations from 35 to 51 - 0%
- [ ] 35) [Embrace linter security rules](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/lintrules.md)
- [ ] 36) [Limit concurrent requests using a balancer or a middleware](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/limitrequests.md)
- [ ] 37) [Common Node.js security best practices](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/commonsecuritybestpractices.md)
- [ ] 38) [Using HTTPS to encrypt the client-server connection](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/secureserver.md)
- [ ] 39) [Using security-related headers to secure your application against common attacks](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/secureheaders.md)
- [ ] 40) [Constantly and automatically inspect for vulnerable dependencies](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/dependencysecurity.md)
- [ ] 41) [Avoid using the Node.js Crypto library for passwords, use Bcrypt](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/bcryptpasswords.md)
- [ ] 42) [Escape Output](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/escape-output.md)
- [ ] 43) [Validate the incoming JSON schemas](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/validation.md)
- [ ] 44) [Support blacklisting JWT tokens](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/expirejwt.md)
- [ ] 45) [Run Node.js as Non-Root User](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/non-root-user.md)
- [ ] 46) [Limit payload size using a reverse-proxy or a middleware](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/requestpayloadsizelimit.md)
- [ ] 47) [Avoid JS eval statements](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/avoideval.md)
- [ ] 48) [Prevent malicious RegEx from overloading your single thread execution](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/regex.md)
- [ ] 49) [Avoid module loading using a variable](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/safemoduleloading.md)
- [ ] 50) [Hide error details from client](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/hideerrors.md)
- [ ] 51) [Modify the default session middleware settings](https://github.com/i0natan/nodebestpractices/blob/master/sections/security/sessions.md)

### CODE REVIEW

**Comment by gianpaj** [comment]
Could you please write in a todo list format ` - [ ] title` what sections are done and what's missing in the translation?
e.g.

- [ ] Project Structure Practices (5)
- [ ] Error Handling Practices (11)
- [ ] Code Style Practices (12)
- [ ] Testing And Overall Quality Practices (10)
- [ ] Going To Production Practices (18)
- [ ] Security Practices (24)
- [ ] Performance Practices (1) (In Progress️ ✍️)


```md
- [ ] Project Structure Practices (5)
- [ ] Error Handling Practices (11)
- [ ] Code Style Practices (12)
- [ ] Testing And Overall Quality Practices (10)
- [ ] Going To Production Practices (18)
- [ ] Security Practices (24)
- [ ] Performance Practices (1) (In Progress️ ✍️)
```

**Comment by desko27** [comment]
@gianpaj ok, I'll try to take a few minutes for it today, maybe tomorrow.

**Comment by i0natan** [comment]
@desko27 Just curious, did we merge all the Excel entries translation we had?

**Comment by desko27** [comment]
@gianpaj I updated the description with the intent of the PR and the current progress 👍

@i0natan as you can see now in the task list, about 50% of the Excel entries were carefully reviewed and introduced into the PR.

I'll write into the main discussion #95 to talk about what the following steps can be. People, thanks again for this wonderful repository, it's very helpful.

**Comment by desko27** [comment]
@i0natan could you add WiP label?

**Comment by i0natan** [comment]
@desko27 to this issue or the home page?

cc @js-kyle

**Comment by desko27** [comment]
Hi guys, just following up on this. I finally had no time on April but I'm having it for May, so let's see if I can complete the remaining 50%!

**Comment by i0natan** [comment]
@desko27 Thanks for the heads-up.

@js-kyle What is the overall status: did we published some Spanish translation? do we want?

**Comment by js-kyle** [comment]
Awesome @desko27! No, it is still a WIP, but I think it is getting very close

**Comment by i0natan** [comment]
@js-kyle @desko27   Anxiously looking forward to accommodating the most popular language in the world :)

**Comment by desko27** [comment]
I'm working on it this weekend guys, I want to move this forward. I'll keep you updated!

**Comment by desko27** [comment]
🗓 Pushing on August. Thanks for your patience.

**Comment by js-kyle** [comment]
As discussed in issue #95, we will merge this, followed by an update to the spanish branch with master

**Pull request merged**
