### PR TITLE
Fix typo.

### PR DESCRIPTION
**Pull request by MasujimaRyohei**

### CODE REVIEW

**Comment by kevynb** [comment]
Hey @MasujimaRyohei thanks for opening a PR to improve the project! 
As my japanese is a little rusty 🙃 , I will kindly ask @YukiOta or @YA21  if they have some time to review the changes you made.

**Review by YukiOta — APPROVED** [review]
Thank you so much @MasujimaRyohei !

@kevynb LGTM!

**Comment by goldbergyoni** [comment]
> As my japanese is a little rusty 🙃

@kevynb 😅😅

**Review by goldbergyoni — APPROVED** [review]
私には素晴らしく見えます

**Comment by goldbergyoni** [comment]
@all-contributors please add @MasujimaRyohei for content

**Pull request merged**
