### PR TITLE
Spanish code style practices

### PR DESCRIPTION
**Pull request by lromano97**
Hello! I'm a native spanish speaker from Argentina and I've translated de codestylepractices section. 

Hope it helps

### CODE REVIEW

**Comment by kevynb** [comment]
Welcome aboard @lromano97 ! 

Thanks for giving us a bit of your time 🕙  It helps a lot!!

We'll ask @desko27 if he has a bit of time to review your changes since he speaks spanish better than us 😉

**Review by desko27 — APPROVED** [review]
@lromano97 Great, just some detail. Thanks for contributing! 👍

**Comment by lromano97** [comment]
Great! Thanks for the review. I'll try to keep on helping as soon as I have extra free time.

**Comment by kevynb** [comment]
That's awesome! Thanks to both of you!

@all-contributors please add @lromano97 for translation

**Pull request merged**
