### PR TITLE
First PR for Japanese translation

### PR DESCRIPTION
**Pull request by YukiOta**
Finally, we've done Japanese translation #768 !

### CODE REVIEW

**Comment by kevynb** [comment]
Impressive work @YukiOta and @YA21 !! You're on 🔥🎆 Thank you so much for the time you took to produce this translation! 🙇‍♂️ 

You can also add the japanese flag in the main `README.md` `Read in a different language` line and in the `#translations` section so that people will know about this new language.

Do not worry about the Contributors sections, you will be automatically added there by our bot :)

We can advertise your contribution on our Twitter if you wish so. If that's the case, give us your Twitter handles so that we can tag you both.

**Comment by YukiOta** [comment]
@kevynb 
Japanese flag is added in `README.md`!

We'd appreciate it if you could tweet our contribution! Our handles are `@yuki_ota_` and `@minmin_yuta`.

**Comment by goldbergyoni** [comment]
@YukiOta Amazing work! So happy to have a Japanese translation 🇯🇵🇯🇵🇯🇵

Let's promote this amazing work as Kevin said.

I can Tweet about it (our account has 9K followers) and put in the news section. Are there some Japanese user groups? Where - FaceBook?

**Review by goldbergyoni — APPROVED** [review]
Epic PR!

**Comment by goldbergyoni** [comment]
p.s. @YukiOta @kevynb Not sure if/when to merge. Is this ready for merge?

**Comment by YukiOta** [comment]
Thank you @goldbergyoni !

> Are there some Japanese user groups? Where - FaceBook?

 As far as I know, there is no active user group on Node.js best practices.
If you need it, let us consider we'll create one.

>  Is this ready for merge?

I believe that it's ready to merge except for the conflicts in `README.md`.

**Review by goldbergyoni — APPROVED** [review]

**Comment by goldbergyoni** [comment]
@YukiOta I meant any Japanese Node.js user group, some place to publish your great work. Whom should be added to the contributor's list?

**Comment by goldbergyoni** [comment]
@all-contributors please add @YukiOta for content

**Comment by YukiOta** [comment]
@goldbergyoni 
I don't see any active Japanese Node.js user group that the work can be published as well 🤔The following is the user group's twitter account.

- https://twitter.com/nodejsjp

And, I'd appreciate it if you could add @YA21 to contributor's list because he did great work too!

**Comment by goldbergyoni** [comment]
@all-contributors please add @YA21  for content

**Comment by goldbergyoni** [comment]
https://twitter.com/nodepractices/status/1359101625101651970

**Comment by goldbergyoni** [comment]
@YA21 @YukiOta No JavaScript user groups in FaceBook or any other platform? How do JS Japanese developers collaborate?

**Pull request merged**
