### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by andrewjbarbour**
-Add missing period to e.g. (e.g -> e.g.) in line 550
-Add a missing apostrophe (end-users -> to end-user's) on line 642 and a missing period on the same line (a.k.a -> a.k.a.)
-Add a code quote to lines 710 and 712 to standardize the formatting of `NODE_ENV` (to match line 714) 
-Fix the markdown code quotes typo in the title of 8.2. on line 1126 ('node' command, avoid npm start -> `node` command, avoid `npm start`)

### CODE REVIEW

**Review by arengoh — DISMISSED** [review]

**Comment by andrewjbarbour** [comment]
Thanks for the review, @arengoh! I'm not quite sure why it says that I dismissed it, which I didn't do. I think it must be some sort of automatic setting that I need to disable. I'll look into it. Thanks again!

**Comment by arengoh** [comment]
Ya mybe . I'm sorry

**Review by arengoh — COMMENTED** [review]
This i got mybe this can fix it.  README.md

**Review by arengoh — COMMENTED** [review]
This one for this .  docs/BestPractices.md

**Comment by arengoh** [comment]
docs/BestPractices.md

**Review by arengoh — COMMENTED** [review]
[README.md]()

**Review by arengoh — COMMENTED** [review]
[sections/docker/bootstrap-using-node.md]()

**Comment by kevynb** [comment]
You have an eagle eye @andrewjbarbour 🦅  ! Thanks for taking the time to submit those fixes. 

Regarding the review dismissal it's because the repository is configured to dismiss approved reviews once you push a new commit. No wrongdoing on your side 😄

**Review by kevynb — APPROVED** [review]

**Pull request merged**
