### PR TITLE
Added another quote for AAA

### PR DESCRIPTION
**Pull request by rluvaton**
Added another quote, the quote is from Bill Wake which he state at the notes of the article that he first observed and name this pattern

And it look like that Martin Fowler support that: 
> Bill Wake came up with the formulation as Arrange, Act, Assert.
> 
> From [Giving When Then](https://martinfowler.com/bliki/GivenWhenThen.html) by Martin Fowler

Related to [this](https://github.com/goldbergyoni/nodebestpractices/projects/1#card-9826386) card

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@rluvaton This is partially related with the item content which is about consistent test structure. The quote however specifically suggest that test should be written bottom-up and start with assertions. While it's a beautiful quote, I'm not sure it related enough. WDYT?

**Comment by rluvaton** [comment]
Agree, but as the creator of AAA I thought it would be important to add him and his advice

**Comment by goldbergyoni** [comment]
@rluvaton Is this one still relevant? I remember seeing another one

**Comment by rluvaton** [comment]
> @rluvaton Is this one still relevant? I remember seeing another one

Yeah, I added 2 quotes

**Comment by goldbergyoni** [comment]
@rluvaton Sorry for the hassle, just fix the conflict and I'll merge right away

**Comment by rluvaton** [comment]
> @rluvaton Sorry for the hassle, just fix the conflict and I'll merge right away

Done

**Review by goldbergyoni — APPROVED** [review]
LGTM

**Pull request merged**
