### PR TITLE
docs: fix typo in the 6.5 chapter of chinese version

### PR DESCRIPTION
**Pull request by ZhyMC**
from the origin english version : 'common security best practices', the chinese title and content should be translated to '通用安全最佳实践' instead of '通用安全最佳实际'

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@ZhyMC Again, it's super imporant to keep our Chinese translation updated. Great work.

@MattJin , Do you happen to have time to review this?

**Review by MattJin — APPROVED** [review]
con！

**Comment by MattJin** [comment]
@ZhyMC thanks to join us

**Comment by ZhyMC** [comment]
@MattJin Thanks for approving, i feel delighted to work with you guys on Chinese-related work.

**Comment by goldbergyoni** [comment]
@ZhyMC Great! 💪✨

 @all-contributors please add @ZhyMC  for content

**Pull request merged**
