### PR TITLE
Update async/await example to resemble promises

### PR DESCRIPTION
**Pull request by leimonio**

### CODE REVIEW

**Comment by goldbergyoni** [comment]
@leimonio Welcome aboard, great addition!

Your name should be added automatically to the contribution list, we have a new bot, let's try if it works

**Comment by leimonio** [comment]
@goldbergyoni glad you approved the update!

**Comment by goldbergyoni** [comment]
@js-kyle Should I do anything in particular to trigger the bot to add a contributor?

**Comment by js-kyle** [comment]
Yeah, instructions are here @goldbergyoni https://github.com/goldbergyoni/nodebestpractices/blob/master/.operations/CONTRIBUTING.md#other-contributions-

@all-contributors-bot please add @leimonio for content

**Comment by leimonio** [comment]
@goldbergyoni @js-kyle thank you a lot! pretty cool feature!

**Pull request merged**
