### PR TITLE
fix(README.md): fix typo

### PR DESCRIPTION
**Pull request by euberdeveloper**
Uppercase letter after ?

### CODE REVIEW

**Review by elektronik2k5 — APPROVED** [review]

**Comment by euberdeveloper** [comment]
I changed just a letter, how could it fail?

**Comment by rluvaton** [comment]
> I changed just a letter, how could it fail?

It failed for different reason 😀

**Review by rluvaton — APPROVED** [review]

**Comment by rluvaton** [comment]
@euberdeveloper thank you for your contribution, hope to see you again soon 😃 

@all-contributors please add @euberdeveloper for content

**Comment by euberdeveloper** [comment]
> @rluvaton
> 
> I've put up [a pull request](https://github.com/goldbergyoni/nodebestpractices/pull/1162) to add @euberdeveloper! 🎉

Thanks! I have seen that an Italian translation is missing, maybe I could help with that

**Comment by rluvaton** [comment]
> Thanks! I have seen that an Italian translation is missing, maybe I could help with that

That's great!, could you please create an issue so we can track its progress 😊

**Pull request merged**
