### PR TITLE
Add Indonesian translation

### PR DESCRIPTION
**Pull request by SuspiciousLookingOwl**
A translation for Indonesian Language.

Progress:
- [x] Introduction & Table of Content
- [x] Section 1 - Project Structure Practices
- [x] Section 2 - Error Handling Practices
- [x] Section 3 - Code Style Practices
- [x] Section 4 - Testing And Overall Quality Practices
- [x] Section 5 - Going To Production Practices
- [x] Section 6 - Security Practices
- [x] Section 7 - Performance Practices
- [x] Section 8 - Docker Practices

### CODE REVIEW

**Comment by SuspiciousLookingOwl** [comment]
@kevynb question, how will the translation be reviewed?

**Comment by kevynb** [comment]
Hello @SuspiciousLookingOwl, that a huge work that you undertook! Thank you so much! Sorry for not dropping by before to answer you question.

> @kevynb question, how will the translation be reviewed?

Well, we had to other people who asked if it was possible to create an indonesian version. We could try to ping them to see if they wish to help with the proof reading. I won't be able to help a lot on that side 😄

**Comment by SuspiciousLookingOwl** [comment]
All good!

I saw that issue before, seems like there aren't a lot of active Indonesian member here. I hope I'm wrong 😄 
I will try my best to reevaluate my work after I finished with everything to minimize any mistakes.

**Comment by goldbergyoni** [comment]
@SuspiciousLookingOwl Just chiming in to say "woowww". That's amazing work!!

I can ask in Twitter for Indonesian developers or maybe you can ask in a local developers group? We may even not review the whole rather only 20% just to get more opinion on the overall writing style

What is the strategy here: Finalize all before publishing or just home page for release (and rest later)?

**Comment by SuspiciousLookingOwl** [comment]
@goldbergyoni 

> I can ask in Twitter for Indonesian developers

That would be great!

> maybe you can ask in a local developers group

Unfortunately, I'm not active in any Indonesian developer group atm.

> Finalize all before publishing or just home page for release (and rest later)?

Just the home page. I'm planning to (slowly) do the `section` part after I finished with this, but that's going to be another PR.

**Comment by ikhsanalatsary** [comment]
@SuspiciousLookingOwl great work.

**Comment by goldbergyoni** [comment]
@SuspiciousLookingOwl Super awesome!

Can you share a brief status: Is the homepage fully translated? How many percentages of the internal pages? We ready to promote this? Did you include your name at the top of the Indonesian homepage?

**Comment by SuspiciousLookingOwl** [comment]
> Is the homepage fully translated

Everything is fully translated except for programming terms (e.g. throw, catch), and link to internal pages on "Read More" part because it's still linking to the English page.

 > How many percentages of the internal pages?
 
 There are no translation done for the internal pages, only the main README
 
 > We ready to promote this?
 
 The `sections` / internal pages has not been translated, Unless it requires full translation on all pages, this should be ready to be promoted. 
 
 >  Did you include your name at the top of the Indonesian homepage?
 
 Where do I put this exactly? Shouldn't it be on the [bottom of the page](https://github.com/goldbergyoni/nodebestpractices/pull/862/files#diff-12482393bc7e091ee3ed126ecd20fcfed8bdd7963d1915b8eb07a598d308522cR1272)?

**Review by goldbergyoni — APPROVED** [review]
Looks super amazing to me

**Comment by goldbergyoni** [comment]
@SuspiciousLookingOwl Amazing

I'll promote this tremendous work shortly by Twitter/news section/etc. What is your Twitter handle? Are there any Indonesian user groups (FB/Discord/Something) where we can promote this?

> Where do I put this exactly? Shouldn't it be on the bottom of the page?

Put your name also at the top of the Indonesian page with a credit to yourself

**Comment by goldbergyoni** [comment]
@all-contributors please add @SuspiciousLookingOwl  for content

**Comment by goldbergyoni** [comment]
@SuspiciousLookingOwl One last question - Did you put the Indonesian flag in the global home page?

**Comment by SuspiciousLookingOwl** [comment]
> What is your Twitter handle

I don't use Twitter / any other social media. A link to my Github user page will do fine!

> Put your name also at the top of the Indonesian page with a credit to yourself

> Did you put the Indonesian flag in the global home page?

Seems like I missed this. I will create another PR in few hours (it's getting late here). 

However I few a questions:

1. Just wanna make sure, by "global", you mean the english version right? (`README.md`)
2. Since I only translated the home page, does it count as `in progress` or not?

**Pull request merged**
