### PR TITLE
Basque translation

### PR DESCRIPTION
**Pull request by anediaz**
The entire README has been translated into Basque, as well as some 'see more' or 'read more' pages.

I've added the Basque as a "translation in progress" at the beginning and the end of each README (except for Korean and Chinese), and I've included my name and my father's as well. 

And also the Basque flag has been added.

### CODE REVIEW

**Comment by kevynb** [comment]
Hey @anediaz let me know when you think the PR is ready. I saw you making fixes so I waited before merging it. :)

**Comment by anediaz** [comment]
Yes good point!!
I'll make some little typo fixes (the main README + the first 4 sections are completely finished!!).
I'll let you know very soon (in some minutes I hope)

**Review by goldbergyoni — APPROVED** [review]
LGTM

**Comment by goldbergyoni** [comment]
@anediaz This is an exciting PR! Amazing work!

I'll start next week to promote this by putting in the news section + Tweets. Are there Spain/Basque user groups somewhere?

**Comment by goldbergyoni** [comment]
@all-contributors please add @anediaz for content

**Pull request merged**
