### PR TITLE
fix the bad code example in same line curly braces

### PR DESCRIPTION
**Pull request by rluvaton**

### CODE REVIEW

**Review by elektronik2k5 — APPROVED** [review]
@rluvaton thanks for fixing!
@goldbergyoni how about we recommend using Prettier instead of all these opinionated rules?

**Comment by rluvaton** [comment]
> @goldbergyoni how about we recommend using Prettier instead of all these opinionated rules?

@elektronik2k5 if we just write to use prettier the reason such specific rules are important will disappear

And as of Prettier documentation, Prettier **is**

> An opinionated code formatter

**Comment by elektronik2k5** [comment]
@rluvaton you're right that both are opinionated, of course. However, Prettier is pretty much considered the industry standard (at least in OSS) and is a very good default. And we already recommend it here anyways. 
So perhaps the the best thing to do is to mention that if you use Prettier (as suggested) then there's no need to format by hand.

**Comment by rluvaton** [comment]
> So perhaps the the best thing to do is to mention that if you use Prettier (as suggested) then there's no need to format by hand.

I think it's a good idea

**Comment by goldbergyoni** [comment]
@rluvaton @elektronik2k5 Agree with both - It's important to understand WHY these rules are important, and practically one should enforce this using Prettier

Where should we add that prettier recommendation?

**Comment by goldbergyoni** [comment]
@rluvaton @elektronik2k5 Agree with both - It's important to understand WHY these rules are important, and practically one should enforce this using Prettier

**Review by goldbergyoni — APPROVED** [review]
LGTM

**Comment by goldbergyoni** [comment]
@all-contributors please add @rluvaton for content

**Comment by goldbergyoni** [comment]
@all-contributors please add @elektronik2k5  for content

**Comment by rluvaton** [comment]
> Where should we add that prettier recommendation?

Right after 3.1 ESLint,
Should we also specify to use prettier plugin with ESLint?

**Pull request merged**
